### ISSUE TITLE
maven / gradle build script

### ISSUE THREAD

**Issue by ghost** [nikhilnanivadekar/ReladomoSample#1]
Hi, 
thank you for providing a sample for reladomo. Would it be possible to add some maven or gradle build scripts? 

Best Regards, 
jj

**Comment by nikhilnanivadekar** [comment]
You find a maven, gradle scripts in this sample: https://github.com/goldmansachs/reladomo/tree/master/samples/reladomo-sample-simple

**Comment by ghost** [comment]
Thanks, I saw them just right now. Ok, let me do a pull request for this project, so that the build scripts are within the sources/projects so that one can do $ git clone ... && gradle build ..

Regards, 
jj

PS : 
Pretty cool project. I;m officially impressed! :-)
